config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'
  resources :notes

end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	before_action :find_note, only: [:show, :edit, :update, :destroy]
	def index
		@notes = Note.all.order("created_at DESC")
	end

	def show
		
	end

	def new
		@note = Note.new
	end

	def create
		@note = Note.new(note_params)

		if @note.save
			redirect_to @note
		else
			render 'new'
		end
	end

	def edit
		
	end

	def update
		
	end

	def destroy
		
	end

	private
	
	def find_note
		@note = Note.find(params[:id])
	end

	def note_params
		params.require(:note).permit(:title, :content)
		
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Notenote</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notes/_form.html.haml
= simple_form_for @note do |f|
	= f.input :title
	= f.input :content
	= f.button :submit

app/views/notes/index.html.haml
- @notes.each do |note|

  %h2= link_to note.title, note
  %p= time_ago_in_words(note.created_at)

app/views/notes/new.html.haml
.wrapper_with_padding
%h1 Add A Note
= render 'form'

app/views/notes/show.html.haml
%h1= @note.title
%p= @note.content

= link_to "All Notes", notes_path

app/views/welcome/index.html.haml
%h1 This is the Placefolder